import streamlit as st
st.title('Title->Geeks for Geeks')
st.header('Header->Geeks for Geeks')
st.subheader('SubHeader->Geeks for Geeks')
st.text('text->Geeks for Geeks')
st.markdown('# Hii')
st.markdown('## Hii')
st.markdown('### Hii')
st.markdown('#### Hii')
st.success('data is submitted')
st.info('Data is submitted')
st.warning('Warning')
st.error('Error')
exp=ZeroDivisionError('Divison not possible by zero')
st.exception(exp)
st.help(ZeroDivisionError)
st.write("range(1,10)")
st.write(range(1,10))
st.write(1+3)
st.code('x=10\n'
        'for i in range(x):\n'
        '\tprint(i)')
st.checkbox('Male')
if(st.checkbox('Adult')):
    st.write('You re an adult')
radiobutton=st.radio('Select :',('Male','Female','Other'))
if(radiobutton=='Male'):
    st.write('You re male')
if(radiobutton=='Female'):
    st.write('You re Female')
if(radiobutton=='Other'):
    st.write('You re Other')  
st.subheader('Select box')
Selectbox=st.selectbox('Select:',['Data Analysis','Machine Learning','Natural Language Processing','Web Scrapping','Computer Vision','Image Processing'])      
st.write('You have selected',Selectbox)
st.subheader('MultiSelectbox')
multiselbox=st.multiselect('Select:',['Data Analysis','Machine Learning','Natural Language Processing','Web Scrapping','Computer Vision','Image Processing'])
st.write("You've selected: ",len(multiselbox),"courses")
st.subheader('Button')
if(st.button('Click me')):
    st.write('Thanks for clicking')
st.subheader('Slider')
vol=st.slider('Select the value',1,100,step=1)
st.write("Volume is",vol)
st.subheader("Text Input")
username=st.text_input("Name:")
password=st.text_input("password:",type='password')
st.subheader("Textarea")
textarea=st.text_area("Write something about yourself")
st.write(textarea)
st.subheader('Input Number')
st.number_input('Select Your age',18,20)
st.subheader('Input Date')
st.date_input('Date')
st.subheader('Input Time ')
st.time_input('Time')

